version: 2

formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: pydatalab/requirements/requirements-all-dev.txt
    - method: pip
      path: ./pydatalab

mkdocs:
  configuration: ./pydatalab/mkdocs.yml
  fail_on_warning: false
